pveclient(1)
============

NAME
----

pveclient - Command line tool to manage Proxmox VE


SYNOPSIS
--------

include::pveclient.1-synopsis.adoc[]


DESCRIPTION
-----------

TODO


Files
-----

`~/.config/pveclient/config`::

Main configuration file used to store remotes.

`~/.config/pveclient/.tickets`::

Cache to store authentification tickets.


Copyright and Disclaimer
------------------------

Copyright (C) 2018 Proxmox Server Solutions GmbH

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public
License along with this program.  If not, see
http://www.gnu.org/licenses/
