#!/usr/bin/perl

use strict;
use warnings;
use lib '/usr/share/pve-client';
use lib '.';
use Data::Dumper;

use PVE::JSONSchema;
use PVE::CLIHandler;

use PVE::APIClient::LWP;
use PVE::APIClient::Helpers;
use PVE::APIClient::Commands::remote;

use JSON;

sub print_usage {

    my $text = "pveclient usage:\n\n";

    $text .= "pveclient remote <help|add|remove> {options}\n\n";

    $text .= "pveclient <get/set/create/delete> <path> {options}\n\n";

    print STDERR $text;

}

sub call_method {
    my ($path, $method, $args) = @_;

    die "missing API path\n" if !defined($path);

    my $info = PVE::APIClient::Helpers::lookup_api_method($path, $method);
    my $param = PVE::JSONSchema::get_options($info->{parameters}, $args);
    print Dumper($param);

    die "implement me";
}

# NOTE: This binary is just a placeholer - nothing implemented so far!

#my $hostname = 'localhost';
#my $username = 'root@pam';
#
#my $conn = PVE::APIClient::LWP->new(
#    username => $username,
#    #password => 'yourpassword',
#    #ticket => $ticket,
#    #csrftoken => $csrftoken,
#    host => $hostname,
#    # allow manual fingerprint verification
#    manual_verification => 1,
#    );

#my $res = $conn->get("/", {});
#print to_json($res, { pretty => 1, canonical => 1});

my $cmd = shift || (print_usage() && exit(-1));

if ($cmd eq 'get') {
    my $method = 'GET';
    my $path;
    if (scalar(@ARGV) && $ARGV[0] !~ m/^\-/)  {
	$path = shift @ARGV;
    }
    my $res = call_method($path, $method, \@ARGV);
    die "implement me";
} elsif ($cmd eq 'set') {
    die "implement me";
} elsif ($cmd eq 'create') {
    die "implement me";
} elsif ($cmd eq 'delete') {
    die "implement me";
} elsif ($cmd eq 'remote') {
    PVE::APIClient::Commands::remote->run_cli_handler();
} else {
    print_usage();
}

exit(0);
